bl_info = {
    "name": "USD Prim Prepended Ref Browser",
    "author": "Auto-generated by GPT assistant",
    "version": (0, 1, 0),
    "blender": (3, 0, 0),
    "location": "View3D > Sidebar (N) > USD Refs",
    "description": "Browse USD prims with prepended references and list their filepaths.",
    "category": "Import-Export",
}

from . import properties as prop
from . import operators as ops
from . import ui as ui_mod


def register() -> None:
    prop.register()
    ops.register()
    ui_mod.register()


def unregister() -> None:
    ui_mod.unregister()
    ops.unregister()
    prop.unregister()


